/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.kjarrio.extractor.SpriteExtractor;
import java.io.*;

public class Sprite2dTK {

    public static void main(String args[]) throws Exception {
        if (args.length != 1 || args[0].equals("--help") || args[0].equals("-h")) {
            System.out.println("Usage: sprite_extractor_2dtk[.jar] [OPTION] SPRITE_SHEET");
            printHelp();
            return;
        }

        String baseName = args[0];
        File spriteSheet = new File(baseName + ".bytes");
        File spriteAtlas = new File(baseName + ".png");

        if (!spriteSheet.exists() || !spriteAtlas.exists()) {
            System.out.println(
                    "Make sure you have both " + baseName + ".bytes and " + baseName + ".png in the same directory.");
            return;
        }

        File outputDir = new File(baseName);
        SpriteExtractor.extract(spriteSheet, outputDir);
    }

    private static void printHelp() {
        String helpMessage = """
                A tool to extract sprites from a 2D Toolkit spritesheet.

                Arguments:
                  SPRITE_SHEET    Base name of the sprite sheet files (without extension).
                                  The tool will look for corresponding .bytes and .png files.

                Options:
                  --help, -h      Show this help message and exit.
                """;
        System.out.println(helpMessage);
    }
}
