/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.kjarrio.extractor.SpriteExtractor;
import java.io.*;

public class Sprite2dTK {

    public static void main(String args[]) throws Exception {
        if (args.length != 1 || args[0].equals("--help") || args[0].equals("-h")) {
            printHelp();
            return;
        }

        String baseName = args[0];
        File bytesFile = new File(baseName + ".bytes");
        File pngFile = new File(baseName + ".png");

        if (!bytesFile.exists()) {
            System.out.println("\033[1;31mError:\033[0m \033[1;33m" + bytesFile.getName()
                    + "\033[0m not found. Make sure you have both \033[1;33m" + bytesFile.getName()
                    + "\033[0m and \033[1;33m" + pngFile.getName() + "\033[0m in the same directory.");
            return;
        }

        if (!pngFile.exists()) {
            System.out.println("\033[1;31mError:\033[0m \033[1;33m" + pngFile.getName()
                    + "\033[0m not found. Make sure you have both \033[1;33m" + bytesFile.getName()
                    + "\033[0m and \033[1;33m" + pngFile.getName() + "\033[0m in the same directory.");
            return;
        }

        File outputDir = new File(baseName);
        SpriteExtractor.extract(bytesFile, outputDir);
    }

    private static void printHelp() {
        String helpMessage = """
                \033[1;34mA tool to extract sprites from a 2D Toolkit spritesheet.

                \033[1;33mUsage:\033[0m
                  sprite_extractor_2dtk.jar \033[38;5;214m[OPTION] \033[1;35mSPRITE_SHEET<.lua,.png>\033[0m

                \033[1;33mArguments:\033[0m
                  \033[1;32mSPRITE_SHEET\033[0m    Base name of the sprite sheet files (without extension).
                                  The tool will look for corresponding .bytes and .png files.

                \033[1;33mOptions:\033[0m
                  \033[1;32m--help, -h\033[0m      Show this help message and exit.
                """;
        System.out.println(helpMessage);
    }
}
