/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.kjarrio.extractor.SpriteExtractor;
import java.io.*;

public class Sprite2dTK {

    public static void main(String args[]) throws Exception {
        if (args.length == 0) {
            System.out.println("Please provide the base name of the sprite sheet.");
            return;
        }

        String baseName = args[0];
        File spriteSheet = new File(baseName + ".bytes");
        File spriteAtlas = new File(baseName + ".png");

        if (!spriteSheet.exists() || !spriteAtlas.exists()) {
            System.out.println(
                    "Make sure you have both " + baseName + ".bytes and " + baseName + ".png in the same directory.");
            return;
        }

        File outputDir = new File(baseName);
        SpriteExtractor.extract(spriteSheet, outputDir);
    }
}
